In [1]:
import pandas as pd

import numpy as np

### Loading dataset in pandas

In [2]:
df = pd.read_csv(r"C:\Users\Lenovo\Downloads\Titanic-Dataset (1).csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Looking the loaded data using head and tail method

In [4]:
df.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [5]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.sample(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
560,561,0,3,"Morrow, Mr. Thomas Rowan",male,NaN,0,0,372622,7.750,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.075,NaN,S
788,789,1,3,"Dean, Master. Bertram Vere",male,1.0,1,2,C.A. 2315,20.575,NaN,S
579,580,1,3,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,7.925,NaN,S

### Display the list of columns in the dataset

In [7]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Selecting the single column and multiple column

In [8]:
df[["PassengerId", "Name", "Age"]]

     PassengerId                                               Name   Age
0              1                            Braund, Mr. Owen Harris  22.0
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2              3                             Heikkinen, Miss. Laina  26.0
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4              5                           Allen, Mr. William Henry  35.0
..           ...                                                ...   ...
886          887                              Montvila, Rev. Juozas  27.0
887          888                       Graham, Miss. Margaret Edith  19.0
888          889           Johnston, Miss. Catherine Helen "Carrie"   NaN
889          890                              Behr, Mr. Karl Howell  26.0
890          891                                Dooley, Mr. Patrick  32.0

[891 rows x 3 columns]

### Slicing in pandas using (loc and iloc)

In [9]:
df.loc[50:100, "Name":"Parch"]

,Name,Sex,Age,SibSp,Parch
50,"Panula, Master. Juha Niilo",male,7.00,4,1
51,"Nosworthy, Mr. Richard Cater",male,21.00,0,0
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0
53,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.00,1,0
54,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1
55,"Woolner, Mr. Hugh",male,NaN,0,0
56,"Rugg, Miss. Emily",female,21.00,0,0
57,"Novel, Mr. Mansouer",male,28.50,0,0
58,"West, Miss. Constance Mirium",female,5.00,1,2
59,"Goodwin, Master. William Frederick",male,11.00,5,2
60,"Sirayanian, Mr. Orsen",male,22.00,0,0
61,"Icard, Miss. Amelie",female,38.00,0,0
62,"Harris, Mr. Henry Birkhardt",male,45.00,1,0
63,"Skoog, Master. Harald",male,4.00,3,2
64,"Stewart, Mr. Albert A",male,NaN,0,0
65,"Moubarek, Master. Gerios",male,NaN,1,1
66,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0
67,"Crease, Mr. Ernest James",male,19.00,0,0
68,"Andersson, Miss. Erna Alexandra",female,17.00,4,2
69,"Kink, Mr. Vincenz",male,26.00,2,0
70,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0
71,"Goodwin, Miss. Lillian Amy",female,16.00,5,2
72,"Hood, Mr. Ambrose Jr",male,21.00,0,0
73,"Chronopoulos, Mr. Apostolos",male,26.00,1,0
74,"Bing, Mr. Lee",male,32.00,0,0
75,"Moen, Mr. Sigurd Hansen",male,25.00,0,0
76,"Staneff, Mr. Ivan",male,NaN,0,0
77,"Moutal, Mr. Rahamin Haim",male,NaN,0,0
78,"Caldwell, Master. Alden Gates",male,0.83,0,2
79,"Dowdell, Miss. Elizabeth",female,30.00,0,0
80,"Waelens, Mr. Achille",male,22.00,0,0
81,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0
82,"McDermott, Miss. Brigdet Delia",female,NaN,0,0
83,"Carrau, Mr. Francisco M",male,28.00,0,0
84,"Ilett, Miss. Bertha",female,17.00,0,0
85,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.00,3,0
86,"Ford, Mr. William Neal",male,16.00,1,3
87,"Slocovski, Mr. Selman Francis",male,NaN,0,0
88,"Fortune, Miss. Mabel Helen",female,23.00,3,2
89,"Celotti, Mr. Francesco",male,24.00,0,0
90,"Christmann, Mr. Emil",male,29.00,0,0
91,"Andreasson, Mr. Paul Edvin",male,20.00,0,0
92,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0
93,"Dean, Mr. Bertram Frank",male,26.00,1,2
94,"Coxon, Mr. Daniel",male,59.00,0,0
95,"Shorney, Mr. Charles Joseph",male,NaN,0,0
96,"Goldschmidt, Mr. George B",male,71.00,0,0
97,"Greenfield, Mr. William Bertram",male,23.00,0,1
98,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1
99,"Kantor, Mr. Sinai",male,34.00,1,0
100,"Petranec, Miss. Matilda",female,28.00,0,0

In [10]:
df.iloc[100:121, 3:8]

                                  Name     Sex   Age  SibSp  Parch
100            Petranec, Miss. Matilda  female  28.0      0      0
101   Petroff, Mr. Pastcho ("Pentcho")    male   NaN      0      0
102          White, Mr. Richard Frasar    male  21.0      0      1
103         Johansson, Mr. Gustaf Joel    male  33.0      0      0
104     Gustafsson, Mr. Anders Vilhelm    male  37.0      2      0
105              Mionoff, Mr. Stoytcho    male  28.0      0      0
106   Salkjelsvik, Miss. Anna Kristine  female  21.0      0      0
107             Moss, Mr. Albert Johan    male   NaN      0      0
108                    Rekic, Mr. Tido    male  38.0      0      0
109                Moran, Miss. Bertha  female   NaN      1      0
110     Porter, Mr. Walter Chamberlain    male  47.0      0      0
111               Zabour, Miss. Hileni  female  14.5      1      0
112             Barton, Mr. David John    male  22.0      0      0
113            Jussila, Miss. Katriina  female  20.0      1      0
114              Attalah, Miss. Malake  female  17.0      0      0
115              Pekoniemi, Mr. Edvard    male  21.0      0      0
116               Connors, Mr. Patrick    male  70.5      0      0
117    Turpin, Mr. William John Robert    male  29.0      1      0
118           Baxter, Mr. Quigg Edmond    male  24.0      0      1
119  Andersson, Miss. Ellis Anna Maria  female   2.0      4      2
120        Hickman, Mr. Stanley George    male  21.0      2      0

### To get random columns

### Getting imformation about the data

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### checking missing values

In [13]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Removing some features(columns)

In [16]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [17]:
df = df.drop(columns = ["PassengerId", "Name", "Ticket"])

In [18]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

### some feature engineering

In [19]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [20]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,FamilySize
0,0,3,male,22.0,1,0,7.2500,NaN,S,2
1,1,1,female,38.0,1,0,71.2833,C85,C,2
2,1,3,female,26.0,0,0,7.9250,NaN,S,1
3,1,1,female,35.0,1,0,53.1000,C123,S,2
4,0,3,male,35.0,0,0,8.0500,NaN,S,1

In [22]:

df = df.drop(columns = ["SibSp", "Parch"])

In [23]:
df.head()

   Survived  Pclass     Sex   Age     Fare Cabin Embarked  FamilySize
0         0       3    male  22.0   7.2500   NaN        S           2
1         1       1  female  38.0  71.2833   C85        C           2
2         1       3  female  26.0   7.9250   NaN        S           1
3         1       1  female  35.0  53.1000  C123        S           2
4         0       3    male  35.0   8.0500   NaN        S           1

# handling the missing values

In [27]:
## for age
mean_age = df["Age"].mean()
mean_age = np.round(mean_age, 2)
# mean_age

# for embarked
mode_embark = df["Embarked"].mode()[0]
mode_embark

'S'

In [26]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [28]:
df["Age"] = df["Age"].fillna(mean_age)
df["Embarked"] = df["Embarked"].fillna(mode_embark)

In [29]:
df.head()

   Survived  Pclass     Sex   Age     Fare Cabin Embarked  FamilySize
0         0       3    male  22.0   7.2500   NaN        S           2
1         1       1  female  38.0  71.2833   C85        C           2
2         1       3  female  26.0   7.9250   NaN        S           1
3         1       1  female  35.0  53.1000  C123        S           2
4         0       3    male  35.0   8.0500   NaN        S           1

In [31]:
df.isnull().sum()

Survived        0
Pclass          0
Sex             0
Age             0
Fare            0
Cabin         687
Embarked        0
FamilySize      0
dtype: int64

In [32]:
df["HasCabin"] = np.where(df["Cabin"].notna(), "Yes", "No")

In [33]:
df.head()

   Survived  Pclass     Sex   Age     Fare Cabin Embarked  FamilySize HasCabin
0         0       3    male  22.0   7.2500   NaN        S           2       No
1         1       1  female  38.0  71.2833   C85        C           2      Yes
2         1       3  female  26.0   7.9250   NaN        S           1       No
3         1       1  female  35.0  53.1000  C123        S           2      Yes
4         0       3    male  35.0   8.0500   NaN        S           1       No

In [34]:
df = df.drop(columns = ["Cabin"])

In [35]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age           0
Fare          0
Embarked      0
FamilySize    0
HasCabin      0
dtype: int64

### Handling categorical features (columns)

In [36]:
df.head()

   Survived  Pclass     Sex   Age     Fare Embarked  FamilySize HasCabin
0         0       3    male  22.0   7.2500        S           2       No
1         1       1  female  38.0  71.2833        C           2      Yes
2         1       3  female  26.0   7.9250        S           1       No
3         1       1  female  35.0  53.1000        S           2      Yes
4         0       3    male  35.0   8.0500        S           1       No

In [37]:
df["Sex"] = df["Sex"].map({"male": 1, "female": 0})

In [38]:
df.head()

   Survived  Pclass  Sex   Age     Fare Embarked  FamilySize HasCabin
0         0       3    1  22.0   7.2500        S           2       No
1         1       1    0  38.0  71.2833        C           2      Yes
2         1       3    0  26.0   7.9250        S           1       No
3         1       1    0  35.0  53.1000        S           2      Yes
4         0       3    1  35.0   8.0500        S           1       No

### saving the cleaned df to csv file

In [39]:
cleaned_df = df.copy()

In [40]:
cleaned_df.head()

   Survived  Pclass  Sex   Age     Fare Embarked  FamilySize HasCabin
0         0       3    1  22.0   7.2500        S           2       No
1         1       1    0  38.0  71.2833        C           2      Yes
2         1       3    0  26.0   7.9250        S           1       No
3         1       1    0  35.0  53.1000        S           2      Yes
4         0       3    1  35.0   8.0500        S           1       No